### ISSUE TITLE
Plugin crashes when MX is missing A record

### ISSUE THREAD

**Issue by lnedry** [haraka/haraka-plugin-spf#13]
### system info

Haraka | Haraka.js — Version: 3.0.1
 --- | :--- 
Node | v18.16.0
OS | Linux mx4 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022

### Expected behavior

Plugin doesn't crash

### Observed behavior

I've noticed two issues and I suspect that they are related. They happen when the domain does not have an A record for its MX server.

1) The plugin crashes with a TypeError.
This is all that shows up in the log:
`Jun 22 05:39:29 mx4 haraka[868630]: [ERROR] [ED649910-3907-4B08-865B-A764A7617251] [TypeError] 
`

2) The SPF test tool, as described in this plugin's readme, also fails with this error:
```
/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-spf/lib/spf.js:504
      self.log_debug(`mech_mx: mx=${mx} addresses=${addrs.join(',')}`);
                                                          ^

TypeError: Cannot read properties of undefined (reading 'join')
    at SPF.mech_mx (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-spf/lib/spf.js:504:59)
    at async SPF.check_host (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-spf/lib/spf.js:290:22)

```

### Steps to reproduce

1) receive email from a domain that doesn't have an A record for its MX server.

2) .../haraka-plugin-spf/bin/spf -ip 57.129.0.61 --domain nagomigyouza.com

**Comment by msimerson** [comment]
thanks for the excellent description. I was able to reproduce, test up a test case, and see the first commit in #14 for the solution. Please test & confirm and I'll merge & release.
