### ISSUE TITLE
need help for setting up SPF

### ISSUE THREAD

**Issue by monperrus** [haraka/haraka-plugin-spf#19]
Hi,

I want to deny incoming messages that violate SPF.

I already have `spf` in `config/plugins`.  

I'm reading the doc, but it's unclear what's the next step.

How to deny incoming messages that violate SPF?

Thanks!

**Comment by msimerson** [comment]
I've made some changes to improve readability. Please try reading the docs at [this link](https://github.com/haraka/haraka-plugin-spf/tree/doc-ini-fences).  Does that help?

Basically, you want to toggle the settings in the `[deny]` section of your spf.ini file from false to true.

**Comment by monperrus** [comment]
thanks a lot @msimerson 

I will try this:

```
[deny]
helo_none=false
helo_softfail=true
helo_fail=true
helo_permerror=false

mfrom_none=false
mfrom_softfail=true
mfrom_fail=true
mfrom_permerror=false

openspf_text=false
```

do `helo_none` and `mfrom_none` mean that the email domain has no SPF entry? what is `permerror`?

**Comment by msimerson** [comment]
> do helo_none and mfrom_none mean that the email domain has no SPF entry?

Yes.

> what is permerror?

See the `Error Handling` section of the [wikipedia entry on SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework)

**Comment by monperrus** [comment]
I confirm that the file `spf.ini` is well loaded `Reloading file: /opt/haraka-smtp/config/spf.ini`.

Consequently I do see in the log `retval=DENY`

```
[INFO] [A4062BFD-96AB-4A4E-981A-A953EBDBB957.1] [core]  hook=mail plugin=spf function=hook_mail params=<spameri@tiscali.it> retval=DENY msg="sender <xxxxxxx@tiscali.it> SPF SoftFail"
```

However, when I test with telnet, I can still continue the sending and get `250 sender <xxxxxxx@tiscali.it> OK`, as if the result of the spf plugin is not taken into account.

Any idea?

Thanks @msimerson

**Comment by msimerson** [comment]
Are you using the karma plugin? If so, add `spf` to `deny_excludes.plugins` in karma.ini.

**Comment by monperrus** [comment]
that works! thanks a lot @msimerson
