### ISSUE TITLE
Plugin crashing

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/haraka-plugin-spf#2]
Edit: It works if I comment out the uses of `skip_hosts`

Any idea why this is crashing?

The content of my `plugins`
```
...
spf
...
```

The content of my `spf.ini`
```
[relay]
context=sender   (default: sender)
```
![image](https://user-images.githubusercontent.com/2115696/185181502-022d2164-6ef9-47e2-8fc7-31db7a99a390.png)

**Comment by lnedry** [comment]
@AuspeXeu Remove the "(default: sender)" from your config.

**Comment by AuspeXeu** [comment]
The issue remains.

**Comment by msimerson** [comment]
Curious: how/why are you using this plugin already?  (I haven't included it in upstream Haraka yet as I haven't had time to test it.)
